version: "3"
services:
    home:
        image: registry.cn-hangzhou.aliyuncs.com/codingwork/home-centos7-php7-nginx:latest
        volumes: 
            - f:/project/linux/docker-space/home:/mnt/docker-space
        networks:
            - my_net
        ports:
            - 80:80
            - 443:443
        hostname: home
        container_name: home
        privileged: true

networks: 
    my_net:
        external:
            name: my_net